import Link from "next/link";
import { supportMatrix } from "../../src/support.ts";

export default function SupportPage() {
  return <><a className="skip-link" href="#main-content">Skip to main content</a><main id="main-content" tabIndex={-1}>
    <header className="topbar"><Link className="brand" href="/" aria-label="Quantum Twin home"><span>QT</span><strong>Quantum <i>Twin</i></strong></Link><nav aria-label="Product"><Link href="/lab">Live lab</Link><Link href="/coverage">NIST coverage</Link><Link href="/demo">Recorded demo</Link></nav></header>
    <section className="intro compact-intro"><div><p className="eyebrow">VERIFIED SUPPORT MATRIX</p><h1>Claims follow proof.</h1><p className="lede">FULLY SUPPORTED requires a detector, adapter, external verifier, positive and negative crypto tests, a system fixture, Windows and Ubuntu proof, and documentation. Missing proof automatically keeps a row experimental or discovery-only.</p></div></section>
    <section><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Boundary</th><th>Level</th><th>Detector</th><th>Adapter</th><th>Verifier</th><th>System fixture</th><th>Windows</th><th>Ubuntu</th></tr></thead><tbody>{supportMatrix.rows.map(row => <tr key={row.boundary}><th>{row.boundary}</th><td><span className={`badge ${row.level === "FULLY_SUPPORTED" ? "live" : "plain"}`}>{row.level.replaceAll("_", " ")}</span></td>{(["detector", "adapter", "verifier", "systemFixture", "windows", "ubuntu"] as const).map(key => <td key={key} className={row[key] ? "pass" : "fail"}>{row[key] ? "YES" : "NO"}</td>)}</tr>)}</tbody></table></div></section>
    <section className="scope"><div><p className="eyebrow">VERIFIED MEANS</p><p>Specified engineering-contract gates passed on the named fixture and platforms. It is not certification, formal verification, production approval, or proof of whole-system quantum safety.</p></div><div><p className="eyebrow">PARTIAL SYSTEMS</p><p>Supported boundaries may still migrate when discovery-only findings exist. Remaining boundaries are reported, not hidden.</p></div><div><p className="eyebrow">SOURCE OF TRUTH</p><p>This page renders directly from <code>support-matrix.json</code>.</p></div></section>
  </main></>;
}
